### PR TITLE
Expose startSpan in the public tracing API

### PR DESCRIPTION
**Pull request by bidetofevil**
## Goal

Expose a new public method to create and start a span at the same time

## Testing

Add all the tests at the right levels

### CODE REVIEW

**Comment by bidetofevil** [comment]
Current dependencies on/for this PR:
* `master`
  * **PR #435** <a href="https://app.graphite.dev/github/pr/embrace-io/embrace-android-sdk/435?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/embrace-io/embrace-android-sdk/435?utm_source=stack-comment).

**Review by fractalwrench — COMMENTED** [review]
Is it worth deprecating createSpan? I worry about making our API too confusing.

LGTM otherwise

**Comment by bidetofevil** [comment]
I will add more docs to make this more clear 😅

**Review by fractalwrench — APPROVED** [review]
LGTM

**Pull request merged**
