### PR TITLE
Only initialize internal interface for the current framework

### PR DESCRIPTION
**Pull request by bidetofevil**
## Goal

We were needlessly initializing the internal interfaces for all frameworks, but we can ever have one, so just do the init for the framework in use - or none at all if we are not running in a hosted SDK environment.

## Testing

Will be added later

### CODE REVIEW

**Comment by bidetofevil** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/embrace-io/embrace-android-sdk/428?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

Current dependencies on/for this PR:
* `master`
  * **PR #425** <a href="https://app.graphite.dev/github/pr/embrace-io/embrace-android-sdk/425?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #426** <a href="https://app.graphite.dev/github/pr/embrace-io/embrace-android-sdk/426?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
      * **PR #427** <a href="https://app.graphite.dev/github/pr/embrace-io/embrace-android-sdk/427?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
        * **PR #428** <a href="https://app.graphite.dev/github/pr/embrace-io/embrace-android-sdk/428?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/embrace-io/embrace-android-sdk/428?utm_source=stack-comment).

**Review by fractalwrench — APPROVED** [review]
LGTM. Do we need to pre-emptively initialize these interfaces at all? Could we simply initialize them lazily when `EmbraceImpl#getUnityInternalInterface` is called for example?

**Comment by bidetofevil** [comment]
### Merge activity

* **Feb 16, 5:11 PM EST**: @bidetofevil started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/embrace-io/embrace-android-sdk/428).

**Comment by bidetofevil** [comment]
The reason did it like this was because I worry about two different threads accessing this the same time, and the documentation for `singleton` said it wasn't threadsafe. This doesn't maximize the effects, but it's safer.

I think when we improve this process of module/service initialization, we can definitely do this lazily.

**Pull request merged**
