### PR TITLE
replace android.util.Pair

### PR DESCRIPTION
**Pull request by nelsitoPuglisi**
## Goal

Use kotlin.Pair instead of android.util.Pair

## Testing

unit testing

### CODE REVIEW

**Comment by nelsitoPuglisi** [comment]
* **#663** <a href="https://app.graphite.dev/github/pr/embrace-io/embrace-android-sdk/663?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#662** <a href="https://app.graphite.dev/github/pr/embrace-io/embrace-android-sdk/662?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @nelsitoPuglisi and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by fractalwrench — APPROVED** [review]
LGTM

**Comment by bidetofevil** [comment]
Should be denylist this class with a detekt rule so if anyone accidentally uses it, it'll get flagged?

**Comment by nelsitoPuglisi** [comment]
> Should be denylist this class with a detekt rule so if anyone accidentally uses it, it'll get flagged?

Sounds good, will add it in this PR.

**Pull request merged**
