### PR TITLE
Add embrace-android-delivery to code coverage tracking

### PR DESCRIPTION
**Pull request by bidetofevil**
## Goal
Adding the delivery modules to code coverage

### CODE REVIEW

**Comment by bidetofevil** [comment]
* **#1475** <a href="https://app.graphite.dev/github/pr/embrace-io/embrace-android-sdk/1475?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @bidetofevil and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by bidetofevil** [comment]
Yeah, I didn't see it be included, so I thought it had to be explicitly stated

**Comment by fractalwrench** [comment]
@bidetofevil thinking further, we can probably simplify this to use something like the following script:

```
// include these projects in code coverage
rootProject.childProjects.forEach { key, proj ->
    if (proj.plugins.hasPlugin("embrace-prod-defaults")) {
        dependencies.add("kover", proj)
    }
}
```

**Comment by bidetofevil** [comment]
Sounds good. Let me modify this.

**Review by fractalwrench — APPROVED** [review]
LGTM

**Comment by bidetofevil** [comment]
### Merge activity

* **Oct 10, 4:07 AM EDT**: A user merged this pull request with [Graphite](https://app.graphite.dev/github/pr/embrace-io/embrace-android-sdk/1475).

**Pull request merged**
