### PR TITLE
Remove Flutter methods from Embrace.java

### PR DESCRIPTION
**Pull request by bidetofevil**
## Goal

Remove Flutter methods from Embrace.java

Note: I will wait for the Flutter team's go-ahead before merging this, as their implementation will need to be updated to use the internal methods instead.

### CODE REVIEW

**Comment by bidetofevil** [comment]
Current dependencies on/for this PR:
* `master`
  * **PR #190** <a href="https://app.graphite.dev/github/pr/embrace-io/embrace-android-sdk/190?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #191** <a href="https://app.graphite.dev/github/pr/embrace-io/embrace-android-sdk/191?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
      * **PR #192** <a href="https://app.graphite.dev/github/pr/embrace-io/embrace-android-sdk/192?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈
        * **PR #193** <a href="https://app.graphite.dev/github/pr/embrace-io/embrace-android-sdk/193?utm_source=stack-comment-icon" target="_blank">Graphite</a> 

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/embrace-io/embrace-android-sdk/192?utm_source=stack-comment).

**Review by fractalwrench — APPROVED** [review]
LGTM

**Comment by leandro-godon** [comment]
@bidetofevil  The Flutter SDK can not use the methods in **FlutterInternalInterface** if its visibility is _internal_, it should be set to _public_.

**Review by leandro-godon — APPROVED** [review]
Tested as working on the Flutter SDK

**Pull request merged**
