### PR TITLE
Use different emulator runner for BP generation

### PR DESCRIPTION
**Pull request by bidetofevil**
## Release Notes

**WHAT**:<br>
**WHY**:<br>

### CODE REVIEW

**Comment by bidetofevil** [comment]
* **#1238** <a href="https://app.graphite.dev/github/pr/embrace-io/embrace-android-sdk/1238?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @bidetofevil and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by fractalwrench — APPROVED** [review]
LGTM

**Review by bidetofevil — COMMENTED** [review]
This still doesn't work :(

**Comment by bidetofevil** [comment]
Different fix required so closing this for now

**Pull request closed without merging**
