### PR TITLE
Move pass through method function implementations of spans API to interface

### PR DESCRIPTION
**Pull request by bidetofevil**
## Goal

Put the method overloads that just call the main method into the interface of the public and internal tracing APIs. 

## Testing

Verified by existing tests

### CODE REVIEW

**Comment by bidetofevil** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/embrace-io/embrace-android-sdk/466?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

Current dependencies on/for this PR:
* **#466** <a href="https://app.graphite.dev/github/pr/embrace-io/embrace-android-sdk/466?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#463** <a href="https://app.graphite.dev/github/pr/embrace-io/embrace-android-sdk/463?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `master`

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/embrace-io/embrace-android-sdk/466?utm_source=stack-comment).

**Review by lucaslabari — APPROVED** [review]
LGTM

**Review by fractalwrench — APPROVED** [review]
LGTM

**Comment by bidetofevil** [comment]
### Merge activity

* **Mar 4, 11:09 AM EST**: @bidetofevil started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/embrace-io/embrace-android-sdk/466).

**Pull request merged**
