### PR TITLE
Expose SDK clock time in through internal tracing API

### PR DESCRIPTION
**Pull request by bidetofevil**
## Goal

Expose a method in the internal tracing API that returns the locked SDK clock time

### CODE REVIEW

**Comment by bidetofevil** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/embrace-io/embrace-android-sdk/392?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

Current dependencies on/for this PR:
* `master`
  * **PR #391** <a href="https://app.graphite.dev/github/pr/embrace-io/embrace-android-sdk/391?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #392** <a href="https://app.graphite.dev/github/pr/embrace-io/embrace-android-sdk/392?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/embrace-io/embrace-android-sdk/392?utm_source=stack-comment).

**Review by fractalwrench — COMMENTED** [review]
I'm happy with the internal refactoring but am not fully convinced that exposing this API is helpful. `recordCompletedSpan` will have already existed, so getting time from `getSdkClockTimeNanos` requires resolving any difference between the customer's timestamp & our timestamp. Customers are also very unlikely to account for device time changes etc.

Has a customer requested this API? If not, I'd suggest ditching the public API. If so, I'd suggest allowing a customer to supply their own implementation of the `Clock` interface for use by the Embrace SDK instead.

**Comment by bidetofevil** [comment]
Not explicitly, no, but I figured they would want this in the future, and for cases where they would use this after app startup.

Lets talk about this further in Slack - but for now, I'll remove the public API and stick this in the internal interface. There's already one that returns the time in millis... so maybe I'll just merge them

**Review by fractalwrench — APPROVED** [review]
LGTM on the basis that the public API part of these changes should be removed from the changeset

**Comment by bidetofevil** [comment]
Discussed this with Jamie. I am also now convinced that we shouldn't expose this, primarily so users won't have to worry about the complexity that this brings.

We'll find another way to reconcile the difference - even if it's just knowing that internally, the times maybe inconsistent if the start/end times are provided by the API user and not the SDK. We can track this internally too with an attribute. I'll post something in slack to further this discussion.

**Comment by bidetofevil** [comment]
### Merge activity

* **Feb 12, 2:44 PM EST**: @bidetofevil started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/embrace-io/embrace-android-sdk/392).

**Pull request merged**
