### PR TITLE
Download androidx.lifecycle dependency version compatible with min AGP version

### PR DESCRIPTION
**Pull request by bidetofevil**
## Goal

`androidx.lifecycle.*:2.8.*` are no compatible with Gradle 7.x. Reverting to a version which seems to be fine.

### CODE REVIEW

**Comment by bidetofevil** [comment]
* **#1644** <a href="https://app.graphite.dev/github/pr/embrace-io/embrace-android-sdk/1644?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @bidetofevil and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by fractalwrench — COMMENTED** [review]
Can we add a note about why higher versions are problematic so we don't experience the same problem in future & forget the reason?

**Comment by bidetofevil** [comment]
Sounds good!

**Review by fractalwrench — APPROVED** [review]
LGTM

**Comment by bidetofevil** [comment]
### Merge activity

* **Nov 8, 12:45 PM EST**: A user merged this pull request with [Graphite](https://app.graphite.dev/github/pr/embrace-io/embrace-android-sdk/1644).

**Pull request merged**
