### PR TITLE
Use logcat sparingly

### PR DESCRIPTION
**Pull request by bidetofevil**
## Goal

Remove all but a couple of logcat output that we would want customers to see. Everything else is basically tracking unexpected behaviour in production, so we either log an internal error or just ignore because ain't no one reading logcat in production dawg.

## Testing
Existing tests pass to ensure functionality wasn't inadvertently broken

### CODE REVIEW

**Comment by bidetofevil** [comment]
* **#1614** <a href="https://app.graphite.dev/github/pr/embrace-io/embrace-android-sdk/1614?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @bidetofevil and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by bidetofevil** [comment]
The only case we use logcat now is when the SDK starts up (info), if erroneous Unity metadata is set (error), and also if the API is being invoked but the SDK wasn't started. We only do this once so as to not flood logcat when the SDK is expected to not be started.

**Review by fractalwrench — APPROVED** [review]
LGTM

**Review by priettt — APPROVED** [review]

**Comment by bidetofevil** [comment]
### Merge activity

* **Nov 1, 2:34 PM EDT**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/embrace-io/embrace-android-sdk/1614).

**Pull request merged**
