### PR TITLE
Update license in README text

### PR DESCRIPTION
**Pull request by davidlawrencer**
## Goal

Updates text in repo's README to reflect Apache license change. See https://github.com/davidlawrencer/embrace-android-sdk?tab=readme-ov-file#license for change.

## Testing

N/A

## Release Notes

N/A

### CODE REVIEW

**Review by lucaslabari — APPROVED** [review]
LGTM

**Comment by davidlawrencer** [comment]
@lucaslabari I think I don't have certain rights on the repo, so the `Run Functional Tests` check failed. Still okay to merge?

**Comment by fractalwrench** [comment]
@davidlawrencer happy for this to be merged without that check as it's a documentation change & can't affect the results of the check

**Comment by davidlawrencer** [comment]
> @davidlawrencer happy for this to be merged without that check as it's a documentation change & can't affect the results of the check

@fractalwrench, makes sense! would you mind re-approving?

**Review by fractalwrench — APPROVED** [review]
LGTM

**Comment by bidetofevil** [comment]
Ari had updated the license already in another PR so we can close this

**Pull request closed without merging**
